services:
  satellite-1:
    build: ./docker
    container_name: SATELLITE-1
    hostname: SATELLITE-1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - /lib/modules:/lib/modules:ro
      - k3s-data-1:/var/lib/rancher/k3s
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.101
    restart: unless-stopped

  satellite-2:
    build: ./docker
    container_name: SATELLITE-2
    hostname: SATELLITE-2
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - /lib/modules:/lib/modules:ro
      - k3s-data-2:/var/lib/rancher/k3s
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.102
    restart: unless-stopped

  satellite-3:
    build: ./docker
    container_name: SATELLITE-3
    hostname: SATELLITE-3
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - /lib/modules:/lib/modules:ro
      - k3s-data-3:/var/lib/rancher/k3s
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.103
    restart: unless-stopped

  satellite-4:
    build: ./docker
    container_name: SATELLITE-4
    hostname: SATELLITE-4
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - /lib/modules:/lib/modules:ro
      - k3s-data-4:/var/lib/rancher/k3s
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.104
    restart: unless-stopped

  satellite-5:
    build: ./docker
    container_name: SATELLITE-5
    hostname: SATELLITE-5
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.105
    restart: unless-stopped

  satellite-6:
    build: ./docker
    container_name: SATELLITE-6
    hostname: SATELLITE-6
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.106
    restart: unless-stopped

  satellite-7:
    build: ./docker
    container_name: SATELLITE-7
    hostname: SATELLITE-7
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.107
    restart: unless-stopped

  satellite-8:
    build: ./docker
    container_name: SATELLITE-8
    hostname: SATELLITE-8
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.108
    restart: unless-stopped

  satellite-9:
    build: ./docker
    container_name: SATELLITE-9
    hostname: SATELLITE-9
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.109
    restart: unless-stopped

  satellite-10:
    build: ./docker
    container_name: SATELLITE-10
    hostname: SATELLITE-10
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.110
    restart: unless-stopped

  satellite-11:
    build: ./docker
    container_name: SATELLITE-11
    hostname: SATELLITE-11
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.111
    restart: unless-stopped

  satellite-12:
    build: ./docker
    container_name: SATELLITE-12
    hostname: SATELLITE-12
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.112
    restart: unless-stopped

  satellite-13:
    build: ./docker
    container_name: SATELLITE-13
    hostname: SATELLITE-13
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.113
    restart: unless-stopped

  satellite-14:
    build: ./docker
    container_name: SATELLITE-14
    hostname: SATELLITE-14
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.114
    restart: unless-stopped

  satellite-15:
    build: ./docker
    container_name: SATELLITE-15
    hostname: SATELLITE-15
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.115
    restart: unless-stopped

  satellite-16:
    build: ./docker
    container_name: SATELLITE-16
    hostname: SATELLITE-16
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.116
    restart: unless-stopped

  satellite-17:
    build: ./docker
    container_name: SATELLITE-17
    hostname: SATELLITE-17
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.117
    restart: unless-stopped

  satellite-18:
    build: ./docker
    container_name: SATELLITE-18
    hostname: SATELLITE-18
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.118
    restart: unless-stopped

  satellite-19:
    build: ./docker
    container_name: SATELLITE-19
    hostname: SATELLITE-19
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.119
    restart: unless-stopped

  satellite-20:
    build: ./docker
    container_name: SATELLITE-20
    hostname: SATELLITE-20
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.120
    restart: unless-stopped

  satellite-21:
    build: ./docker
    container_name: SATELLITE-21
    hostname: SATELLITE-21
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.121
    restart: unless-stopped

  satellite-22:
    build: ./docker
    container_name: SATELLITE-22
    hostname: SATELLITE-22
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.122
    restart: unless-stopped

  satellite-23:
    build: ./docker
    container_name: SATELLITE-23
    hostname: SATELLITE-23
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.123
    restart: unless-stopped

  satellite-24:
    build: ./docker
    container_name: SATELLITE-24
    hostname: SATELLITE-24
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.124
    restart: unless-stopped

  satellite-25:
    build: ./docker
    container_name: SATELLITE-25
    hostname: SATELLITE-25
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.125
    restart: unless-stopped

  satellite-26:
    build: ./docker
    container_name: SATELLITE-26
    hostname: SATELLITE-26
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.126
    restart: unless-stopped

  satellite-27:
    build: ./docker
    container_name: SATELLITE-27
    hostname: SATELLITE-27
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.127
    restart: unless-stopped

  satellite-28:
    build: ./docker
    container_name: SATELLITE-28
    hostname: SATELLITE-28
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.128
    restart: unless-stopped

  satellite-29:
    build: ./docker
    container_name: SATELLITE-29
    hostname: SATELLITE-29
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.129
    restart: unless-stopped

  satellite-30:
    build: ./docker
    container_name: SATELLITE-30
    hostname: SATELLITE-30
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.130
    restart: unless-stopped

  satellite-31:
    build: ./docker
    container_name: SATELLITE-31
    hostname: SATELLITE-31
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.131
    restart: unless-stopped

  satellite-32:
    build: ./docker
    container_name: SATELLITE-32
    hostname: SATELLITE-32
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.132
    restart: unless-stopped

  satellite-33:
    build: ./docker
    container_name: SATELLITE-33
    hostname: SATELLITE-33
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.133
    restart: unless-stopped

  satellite-34:
    build: ./docker
    container_name: SATELLITE-34
    hostname: SATELLITE-34
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.134
    restart: unless-stopped

  satellite-35:
    build: ./docker
    container_name: SATELLITE-35
    hostname: SATELLITE-35
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.135
    restart: unless-stopped

  satellite-36:
    build: ./docker
    container_name: SATELLITE-36
    hostname: SATELLITE-36
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.136
    restart: unless-stopped

  satellite-37:
    build: ./docker
    container_name: SATELLITE-37
    hostname: SATELLITE-37
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.137
    restart: unless-stopped

  satellite-38:
    build: ./docker
    container_name: SATELLITE-38
    hostname: SATELLITE-38
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.138
    restart: unless-stopped

  satellite-39:
    build: ./docker
    container_name: SATELLITE-39
    hostname: SATELLITE-39
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.139
    restart: unless-stopped

  satellite-40:
    build: ./docker
    container_name: SATELLITE-40
    hostname: SATELLITE-40
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.140
    restart: unless-stopped

  satellite-41:
    build: ./docker
    container_name: SATELLITE-41
    hostname: SATELLITE-41
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.141
    restart: unless-stopped

  satellite-42:
    build: ./docker
    container_name: SATELLITE-42
    hostname: SATELLITE-42
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.142
    restart: unless-stopped

  satellite-43:
    build: ./docker
    container_name: SATELLITE-43
    hostname: SATELLITE-43
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.143
    restart: unless-stopped

  satellite-44:
    build: ./docker
    container_name: SATELLITE-44
    hostname: SATELLITE-44
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.144
    restart: unless-stopped

  satellite-45:
    build: ./docker
    container_name: SATELLITE-45
    hostname: SATELLITE-45
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.145
    restart: unless-stopped

  satellite-46:
    build: ./docker
    container_name: SATELLITE-46
    hostname: SATELLITE-46
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.146
    restart: unless-stopped

  satellite-47:
    build: ./docker
    container_name: SATELLITE-47
    hostname: SATELLITE-47
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.147
    restart: unless-stopped

  satellite-48:
    build: ./docker
    container_name: SATELLITE-48
    hostname: SATELLITE-48
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.148
    restart: unless-stopped

  satellite-49:
    build: ./docker
    container_name: SATELLITE-49
    hostname: SATELLITE-49
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.149
    restart: unless-stopped

  satellite-50:
    build: ./docker
    container_name: SATELLITE-50
    hostname: SATELLITE-50
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.150
    restart: unless-stopped

  satellite-51:
    build: ./docker
    container_name: SATELLITE-51
    hostname: SATELLITE-51
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.151
    restart: unless-stopped

  satellite-52:
    build: ./docker
    container_name: SATELLITE-52
    hostname: SATELLITE-52
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.152
    restart: unless-stopped

  satellite-53:
    build: ./docker
    container_name: SATELLITE-53
    hostname: SATELLITE-53
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.153
    restart: unless-stopped

  satellite-54:
    build: ./docker
    container_name: SATELLITE-54
    hostname: SATELLITE-54
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.154
    restart: unless-stopped

  satellite-55:
    build: ./docker
    container_name: SATELLITE-55
    hostname: SATELLITE-55
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.155
    restart: unless-stopped

  satellite-56:
    build: ./docker
    container_name: SATELLITE-56
    hostname: SATELLITE-56
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.156
    restart: unless-stopped

  satellite-57:
    build: ./docker
    container_name: SATELLITE-57
    hostname: SATELLITE-57
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.157
    restart: unless-stopped

  satellite-58:
    build: ./docker
    container_name: SATELLITE-58
    hostname: SATELLITE-58
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.158
    restart: unless-stopped

  satellite-59:
    build: ./docker
    container_name: SATELLITE-59
    hostname: SATELLITE-59
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.159
    restart: unless-stopped

  satellite-60:
    build: ./docker
    container_name: SATELLITE-60
    hostname: SATELLITE-60
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.160
    restart: unless-stopped

  satellite-61:
    build: ./docker
    container_name: SATELLITE-61
    hostname: SATELLITE-61
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.161
    restart: unless-stopped

  satellite-62:
    build: ./docker
    container_name: SATELLITE-62
    hostname: SATELLITE-62
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.162
    restart: unless-stopped

  satellite-63:
    build: ./docker
    container_name: SATELLITE-63
    hostname: SATELLITE-63
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.163
    restart: unless-stopped

  satellite-64:
    build: ./docker
    container_name: SATELLITE-64
    hostname: SATELLITE-64
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.164
    restart: unless-stopped

  ibi_es:
    build: ./docker
    container_name: Ibi_ES
    hostname: Ibi_ES
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.201
    restart: unless-stopped

  foggia_it:
    build: ./docker
    container_name: Foggia_IT
    hostname: Foggia_IT
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.202
    restart: unless-stopped

volumes:
  k3s-data-1:
  k3s-data-2:
  k3s-data-3:
  k3s-data-4:

networks:
  vsnes:
    name: vsnes_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.12.0/24
