services:
  satellite-1:
    build: ./docker
    container_name: SAT-1
    hostname: SAT-1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - /lib/modules:/lib/modules:ro
      - k3s-data-1:/var/lib/rancher/k3s
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.101
    restart: unless-stopped

  satellite-2:
    build: ./docker
    container_name: SAT-2
    hostname: SAT-2
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - /lib/modules:/lib/modules:ro
      - k3s-data-2:/var/lib/rancher/k3s
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.102
    restart: unless-stopped

  satellite-3:
    build: ./docker
    container_name: SAT-3
    hostname: SAT-3
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - /lib/modules:/lib/modules:ro
      - k3s-data-3:/var/lib/rancher/k3s
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.103
    restart: unless-stopped

  satellite-4:
    build: ./docker
    container_name: SAT-4
    hostname: SAT-4
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - /lib/modules:/lib/modules:ro
      - k3s-data-4:/var/lib/rancher/k3s
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.104
    restart: unless-stopped

  satellite-5:
    build: ./docker
    container_name: SAT-5
    hostname: SAT-5
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.105
    restart: unless-stopped

  satellite-6:
    build: ./docker
    container_name: SAT-6
    hostname: SAT-6
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.106
    restart: unless-stopped

  satellite-7:
    build: ./docker
    container_name: SAT-7
    hostname: SAT-7
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.107
    restart: unless-stopped

  satellite-8:
    build: ./docker
    container_name: SAT-8
    hostname: SAT-8
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.108
    restart: unless-stopped

  satellite-9:
    build: ./docker
    container_name: SAT-9
    hostname: SAT-9
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.109
    restart: unless-stopped

  satellite-10:
    build: ./docker
    container_name: SAT-10
    hostname: SAT-10
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.110
    restart: unless-stopped

  satellite-11:
    build: ./docker
    container_name: SAT-11
    hostname: SAT-11
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.111
    restart: unless-stopped

  satellite-12:
    build: ./docker
    container_name: SAT-12
    hostname: SAT-12
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.112
    restart: unless-stopped

  

  ibi_es:
    build: ./docker
    container_name: Ibi_ES
    hostname: Ibi_ES
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.201
    restart: unless-stopped

  foggia_it:
    build: ./docker
    container_name: Foggia_IT
    hostname: Foggia_IT
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vsnes:
        ipv4_address: 172.27.12.202
    restart: unless-stopped

volumes:
  k3s-data-1:
  k3s-data-2:
  k3s-data-3:
  k3s-data-4:

networks:
  vsnes:
    name: vsnes_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.12.0/24
